### ISSUE TITLE
Brush tool crashes

### ISSUE THREAD

**Issue by chowdhuryqaizar** [altis-labs/cornerstoneTools#22]
#### Describe the bug
Using the brush tool to remove contour mask by pressing the "Control key" crashes nota-annotate.

#### To Reproduce
1. Go to 'brush tool'
2. Click in the study somewhere
3. Click on "control" and drag the tool over the existing mask
4. Screen turns white after a moment

#### Expected behavior
The contour disappears.

**Comment by mkramers** [comment]
Fixed by https://github.com/altis-labs/nota/pull/1156
